project_id = "joboegjaowcwulqitchu"

[functions.send-support-ticket]
verify_jwt = false

[functions.notify-ticket-reply]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.send-telegram-verification]
verify_jwt = false

[functions.send-password-reset-otp]
verify_jwt = false

[functions.verify-password-reset-otp]
verify_jwt = false

[functions.notify-user-banned]
verify_jwt = false

[functions.track-session]
verify_jwt = false

[functions.submit-ban-appeal]
verify_jwt = false

[functions.auto-unban]
verify_jwt = false

[functions.notify-topup-status]
verify_jwt = false

[functions.notify-topup-proof]
verify_jwt = false

[functions.check-verification-status]
verify_jwt = false

[functions.check-email-availability]
verify_jwt = false

[functions.check-telegram-availability]
verify_jwt = false

[functions.get-telegram-profile]
verify_jwt = false

[functions.send-deletion-otp]
verify_jwt = false

[functions.verify-deletion-otp]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.bin-lookup]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.check-device-block]
verify_jwt = false

[functions.log-device]
verify_jwt = false

[functions.paygate-check]
verify_jwt = false

[functions.notify-charged-card]
verify_jwt = false

[functions.deduct-credits]
verify_jwt = false

[functions.braintree-auth-check]
verify_jwt = false

[functions.stripe-auth-check]
verify_jwt = false

[functions.payu-check]
verify_jwt = false

[functions.notify-credit-addition]
verify_jwt = false

[functions.notify-ticket-status]
verify_jwt = false

[functions.combined-auth-check]
verify_jwt = false

[functions.notify-registration]
verify_jwt = false

[functions.notify-login]
verify_jwt = false

[functions.import-urls]
verify_jwt = false

[functions.stripe-charge-check]
verify_jwt = false

[functions.pwgate-charge-check]
verify_jwt = false

[functions.braintree-auth-batch-check]
verify_jwt = false
