project_id = "joboegjaowcwulqitchu"

[functions.send-support-ticket]
verify_jwt = false

[functions.notify-ticket-reply]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.send-telegram-verification]
verify_jwt = false

[functions.send-password-reset-otp]
verify_jwt = false

[functions.verify-password-reset-otp]
verify_jwt = false

[functions.notify-user-banned]
verify_jwt = false

[functions.track-session]
verify_jwt = false

[functions.submit-ban-appeal]
verify_jwt = false