project_id = "joboegjaowcwulqitchu"

[functions.send-support-ticket]
verify_jwt = false

[functions.notify-ticket-reply]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.send-telegram-verification]
verify_jwt = false
